### PR TITLE
Tidyup & upgrade dependencies

### PR DESCRIPTION
**Pull request by mh-trimble**
Hey I saw the plugin and thought I'd upgrade the dependencies.

Doing that I decided to refactor the code a bit and add a bit of structure to the project, I hope the code is a bit more readable.

I added `strict: true` in the tsconfig to catch a few potential errors on the way.

Before I start annotating my changes, I'd like to test them - how would I do that?

### CODE REVIEW

**Comment by alensiljak** [comment]
Hi, Martin! Thanks for the contribution.

I am not aware of any specific methods for automated testing of Obsidian plugins, unfortunately. You may want to research that topic. I assume regular unit tests would do. Of which we don't have any at the moment, I believe.

**Comment by epsilonhalbe** [comment]
makes sense to move and then change,

how do I manually test the plugin, do i just copy the folder into my plugins folder?

**Comment by alensiljak** [comment]
Yes, just putting the code into a plugin subfolder should work.

https://forum.obsidian.md/t/how-to-evaluate-variable-values-and-test-my-obsidian-plugin-written-in-typescript/47650

**Comment by mh-trimble** [comment]
i fixed preserving the file history issue

**Comment by mh-trimble** [comment]
also moved from rollup to esbuild since i misremembered rollup being not developed anymore, esbuild though is super fast and equally easy to configure.

I also added eslint and prettier since there was no uniform style

**Review by alensiljak — APPROVED** [review]
Thank you for contributing!

**Comment by alensiljak** [comment]
Sorry, we got #46 so I've reverted the changes. Doesn't seem to be a good idea to shuffle files around without checking the Obsidian plugin documentation. ;)

**Pull request merged**
